/* 题库独立于界面。新增卡片请使用唯一 id，type 为 action / image / quick。 */
window.CHALLENGE_CARDS = [
  {id:'A01',type:'action',title:'忍者结印',task:'模仿一个《火影忍者》里的结印动作，坚持3秒。',source:'火影忍者',seconds:10},
  {id:'A02',type:'action',title:'龟派气功',task:'摆出一次经典龟派气功蓄力姿势。',source:'龙珠',seconds:10},
  {id:'A03',type:'action',title:'名侦探出场',task:'模仿柯南指出真相时的经典动作。',source:'名侦探柯南',seconds:10},
  {id:'A04',type:'action',title:'宝可梦训练家',task:'做一个扔出精灵球的动作，不需要喊台词。',source:'宝可梦',seconds:10},
  {id:'A05',type:'action',title:'动漫剑士拔刀',task:'模仿动漫剑士准备拔刀的姿势。',source:'动漫 · 自由选择',seconds:10},
  {id:'A06',type:'action',title:'游戏角色待机',task:'模仿一个自己熟悉的游戏角色待机动作。',source:'游戏 · 自由选择',seconds:10},
  {id:'A07',type:'action',title:'原神开大',task:'任选一个熟悉的《原神》角色，模仿TA释放元素爆发时的姿势。',source:'原神',seconds:15},
  {id:'A08',type:'action',title:'崩铁终结技',task:'任选一个熟悉的《崩坏：星穹铁道》角色，模仿TA释放终结技时的动作。',source:'崩坏：星穹铁道',seconds:15},
  {id:'A09',type:'action',title:'王者英雄登场',task:'任选一个熟悉的《王者荣耀》英雄，模仿TA的经典动作。',source:'王者荣耀',seconds:15},
  {id:'A10',type:'action',title:'第五人格角色模仿',task:'任选一个《第五人格》求生者或监管者，模仿TA的代表动作。',source:'第五人格',seconds:15},
  {id:'A11',type:'action',title:'主角登场',task:'摆一个自己认为很像动漫主角登场的动作。',source:'动漫 · 自由发挥',seconds:10},
  {id:'A12',type:'action',title:'自由模仿',task:'选择一个动漫或游戏角色，用动作模仿TA，让现场工作人员猜。',source:'动漫 / 游戏 · 自由选择',seconds:30},
  {id:'I01',type:'image',title:'五条悟',source:'咒术回战',guess:'assets/images/I01_guess.jpg',answer:'assets/images/I01_answer.jpg',seconds:30},
  {id:'I02',type:'image',title:'灶门炭治郎',source:'鬼灭之刃',guess:'assets/images/I02_guess.jpg',answer:'assets/images/I02_answer.jpg',seconds:30},
  {id:'I03',type:'image',title:'阿尼亚',source:'间谍过家家',guess:'assets/images/I03_guess.jpg',answer:'assets/images/I03_answer.jpg',seconds:30},
  {id:'I04',type:'image',title:'漩涡鸣人',source:'火影忍者',guess:'assets/images/I04_guess.jpg',answer:'assets/images/I04_answer.jpg',seconds:30},
  {id:'I05',type:'image',title:'胡桃',source:'原神',guess:'assets/images/I05_guess.jpg',answer:'assets/images/I05_answer.jpg',seconds:30},
  {id:'I06',type:'image',title:'雷电将军',source:'原神',guess:'assets/images/I06_guess.jpg',answer:'assets/images/I06_answer.jpg',seconds:30},
  {id:'I07',type:'image',title:'三月七',source:'崩坏：星穹铁道',guess:'assets/images/I07_guess.jpg',answer:'assets/images/I07_answer.jpg',seconds:30},
  {id:'I08',type:'image',title:'邦布',source:'绝区零',guess:'assets/images/I08_guess.jpg',answer:'assets/images/I08_answer.jpg',seconds:30},
  {id:'I09',type:'image',title:'李白',source:'王者荣耀',guess:'assets/images/I09_guess.jpg',answer:'assets/images/I09_answer.jpg',seconds:30},
  {id:'I10',type:'image',title:'瑶',source:'王者荣耀',guess:'assets/images/I10_guess.jpg',answer:'assets/images/I10_answer.jpg',seconds:30},
  {id:'I11',type:'image',title:'红蝶',source:'第五人格',guess:'assets/images/I11_guess.jpg',answer:'assets/images/I11_answer.jpg',seconds:30},
  {id:'I12',type:'image',title:'园丁',source:'第五人格',guess:'assets/images/I12_guess.jpg',answer:'assets/images/I12_answer.jpg',seconds:30},
  {id:'Q01',type:'quick',title:'15秒皮卡丘',task:'15秒内画出皮卡丘，让现场至少一个人认出来。',source:'宝可梦',seconds:15},
  {id:'Q02',type:'quick',title:'15秒派蒙',task:'15秒内画出派蒙，让现场的人认出来。',source:'原神',seconds:15},
  {id:'Q03',type:'quick',title:'灵魂画手',task:'15秒内画一个自己喜欢的动漫或游戏角色，让工作人员猜。',source:'动漫 / 游戏 · 自由选择',seconds:15},
  {id:'Q04',type:'quick',title:'闭眼速画',task:'闭眼10秒画一个熟悉的角色头像。',source:'动漫 / 游戏 · 自由选择',seconds:10},
  {id:'Q05',type:'quick',title:'三部热门动漫',task:'10秒内说出3部自己看过或听说过的动漫。',source:'动漫 · 自由选择',seconds:10},
  {id:'Q06',type:'quick',title:'三个动漫主角',task:'10秒内说出3个不同作品的动漫主角。',source:'动漫 · 自由选择',seconds:10},
  {id:'Q07',type:'quick',title:'三个原神角色',task:'10秒内说出3个《原神》角色。',source:'原神',seconds:10},
  {id:'Q08',type:'quick',title:'三个崩铁角色',task:'10秒内说出3个《崩坏：星穹铁道》角色。',source:'崩坏：星穹铁道',seconds:10},
  {id:'Q09',type:'quick',title:'三个王者英雄',task:'10秒内说出3个《王者荣耀》英雄。',source:'王者荣耀',seconds:10},
  {id:'Q10',type:'quick',title:'三个第五人格角色',task:'10秒内说出3个《第五人格》角色。',source:'第五人格',seconds:10},
  {id:'Q11',type:'quick',title:'三个二游',task:'10秒内说出3款二次元游戏。',source:'二次元游戏 · 自由选择',seconds:10},
  {id:'Q12',type:'quick',title:'终极自由题',task:'10秒内连续说出5个动漫或游戏角色，不能重复。',source:'动漫 / 游戏 · 自由选择',seconds:10}
];
